# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- script: |
    # Update the Azure Repo
    git config --global user.email "aishwaryalonarkar@gmail.com"
    git config --global user.name "aishwarya.lonarkar"
    
    git remote add azure https://ystaservices@dev.azure.com/ystaservices/Testing%20Project/_git/Testing%20Project
    git config --global credential.helper '!f() { sleep 1; echo "username=aishwarya.lonarkar"; echo "password=dlmt7sam5aijwigjhduothmm2i33zruqgdxtwhv62zsbj3tk3ajq"; }; f'
    git fetch --all
    git push azure --mirror
    # git push azure HEAD:refs/heads/main --force

    # git remote add azure https://aishwarya.lonarkar@ystas.com/MyProject/MyRepo/_git/MyRepo
    # git remote add azure https://<username>:<personal-access-token>@dev.azure.com/<organization>/<project>/_git/<repository>
    # git remote add azure https://ystaservices@dev.azure.com/ystaservices/Testing%20Project/_git/Testing%20Project # Replace with the URL of your Azure Repo
    
    git push azure HEAD:refs/heads/main --force  # Replace 'main' with the appropriate branch name

  displayName: Update Azure Repo version 2
